jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('OS:{0} PY:{1}', image, pythonVersion) }}

        pool:
          vmImage: ${{ image }}

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true

          - script: export AZURE_BUILD=1
            displayName: 'setting eenvironment variables'

          - script: brew install --force llvm libffi cmake ninja make
              displayName: 'Install libs'

          - script: python3 make.py macOS submodules clean mpy_cross DISPLAY=sdl_display INDEV=sdl_pointer
              displayName: 'unix port (SDL)'
