jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('OS:{0} PY:{1}', image, pythonVersion) }}

        pool:
          vmImage: ${{ image }}
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true

          - script: set AZURE_BUILD=1
          - script: python -m pip install --upgrade pip setuptools wheel
          - script: python -m pip install pyMSVC
          - script: python3 make.py windows submodules clean mpy_cross DISPLAY=sdl_display INDEV=sdl_pointer
