name: macOS build
on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Install Dependencies
      run: |
        brew install --force gcc libffi cmake ninja make
        brew install --force --cask gcc-arm-embedded

    - name: Build macOS port
      run: python3 make.py unix submodules clean mpy_cross DISPLAY=sdl_display INDEV=sdl_pointer

    - name: Build ESP32 port
      run: python3 make.py esp32 submodules clean mpy_cross BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=gt911

    - name: Build STM32 port
      run: python3 make.py stm32 submodules clean mpy_cross BOARD=STM32F7DISC DISPLAY=rgb_display INDEV=gt911

    - name: Build Raspberry Pi PICO port
      run: python3 make.py rp2 submodules clean mpy_cross BOARD=RPI_PICO DISPLAY=rgb_display INDEV=gt911
