name: Unix build

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/gcc-problem-matcher@master
    - uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install --assume-yes --allow-downgrades --allow-remove-essential --allow-change-held-packages build-essential pkg-config cmake ninja-build libffi-dev gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev ccache

    - name: Cached Deps
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: lib/
        key: ${{ runner.os }}-deps

    - name: Get Build Deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        git submodule update --init lib/pycparser lib/micropython lib/esp-idf lib/lvgl lib/SDL
        git checkout v1.23.0 -- lib/micropython
        git checkout master -- lib/lvgl
        git checkout release-2.30.2 -- lib/SDL
        
        export "IDF_PATH=${GITHUB_WORKSPACE}/lib/esp-idf"
        git submodule update --init lib/esp-idf/components/bt/host/nimble/nimble lib/esp-idf/components/esp_wifi lib/esp-idf/components/esptool_py/esptool lib/esp-idf/components/lwip/lwip lib/esp-idf/components/mbedtls/mbedtls lib/esp-idf/components/bt/controller/lib_esp32 lib/esp-idf/components/bt/controller/lib_esp32c3_family
        ./lib/esp-idf/install.sh all
        . ./lib/esp-idf/export.sh

    - name: Build ESP32 port
      run: python3 make.py esp32 submodules clean mpy_cross BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=gt911 --ccache

    - name: Build STM32 port
      run: python3 make.py stm32 submodules clean mpy_cross BOARD=STM32H7B3I_DK DISPLAY=rgb_display INDEV=gt911

    - name: Build Raspberry Pi PICO port
      run: python3 make.py rp2 submodules clean mpy_cross BOARD=RPI_PICO DISPLAY=rgb_display INDEV=gt911

    - name: Build Unix port
      run: python3 make.py unix submodules clean mpy_cross DISPLAY=sdl_display INDEV=sdl_pointer
