name: Windows build

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Cyberboss/install-winget@v1
    - uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: ./.github/actions/esp-idf-action
      with:
        esp_idf_version: v5.0.4
        esp_idf_target: esp32s3

    - name: Install Dependencies
      run: |
        winget install --accept-source-agreements --accept-package-agreements ezwinports.make
        python3 -m pip install pyMSVC

    - name: Build ESP32 port
      run: python3 make.py esp32 submodules clean mpy_cross BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=gt911

    - name: Build STM32 port
      run: python3 make.py stm32 submodules clean mpy_cross BOARD=STM32F7DISC DISPLAY=rgb_display INDEV=gt911

    - name: Build Raspberry Pi PICO port
      run: python3 make.py rp2 submodules clean mpy_cross BOARD=RPI_PICO DISPLAY=rgb_display INDEV=gt911

    - name: Build Windows port
      run: python3 make.py windows submodules clean mpy_cross DISPLAY=sdl_display INDEV=sdl_pointer


